# This is the docker-compose file to run Medplum's required background serivces
# It can be used to quickly run 2 services:
#   1) The Postgres database
#   2) The Redis cache
# You can start all services by running "docker-compose up"
version: '3.7'
services:

  app: 
    container_name: medplum-app
    build: 
      context: ./
      dockerfile: ./packages/app/Dockerfile
    depends_on:
      - server
    environment: 
      - MEDPLUM_BASE_URL=http://${MEDPLUM_HOST}:${MEDPLUM_PORT}/
    networks:
      - medplum_network
    ports: 
      - 3482:3000
    restart: unless-stopped 

  server:
    container_name: medplum-server
    build: 
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTMARK_API_TOKEN
    hostname: ${MEDPLUM_HOST}
    networks: 
      - medplum_network
    ports:
      - 8103:${MEDPLUM_PORT}
    restart: unless-stopped
    volumes: 
      - ./packages/:/usr/src/medplum/packages/

  postgres:
    container_name: medplum-postgres
    image: postgres:12
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ./postgres/postgres.conf:/usr/local/etc/postgres/postgres.conf
      - ./postgres/:/docker-entrypoint-initdb.d/
      - ../postgres/data/:/var/lib/postgresql/data/
    command: postgres -c config_file=/usr/local/etc/postgres/postgres.conf
    ports:
      - 5432:${POSTGRES_PORT}
    networks:
      - medplum_network
    hostname: ${POSTGRES_HOST}

  redis:
    container_name: medplum-redis
    image: redis:6
    command: redis-server --requirepass ${REDIS_PASSWORD}
    hostname: ${REDIS_HOST}
    ports:
      - 6379:${REDIS_PORT}
    networks:
      - medplum_network

networks: 
  medplum_network: 
    name: medplum_network