# This is the docker-compose file to run Medplum's required background serivces
# It can be used to quickly run 2 services:
#   1) The Postgres database
#   2) The Redis cache
# You can start all services by running "docker-compose up"
version: '3.7'
services:

  app: 
    container_name: medplum-app
    build: 
      context: ./
      dockerfile: ./packages/app/Dockerfile
    depends_on:
      - server
      - proxy
    environment: 
      - MEDPLUM_BASE_URL=http://localhost:${NGINX_HTTP_PORT}/
    networks:
      - medplum_network
    ports: 
      - 3482:3000
    restart: unless-stopped 

  server:
    container_name: medplum-server
    build: 
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT=${POSTGRES_PORT_CONTAINER}
      - POSTMARK_API_TOKEN
      # - HTTP_PROXY
      # - HTTPS_PROXY
    hostname: ${MEDPLUM_HOST}
    networks: 
      - medplum_network
    ports:
      - ${MEDPLUM_PORT_HOST}:${MEDPLUM_PORT_CONTAINER}
    restart: unless-stopped
    volumes: 
      - ./packages/:/usr/src/medplum/packages/

  postgres:
    container_name: medplum-postgres
    image: postgres:12
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ./postgres/postgres.conf:/usr/local/etc/postgres/postgres.conf
      - ./postgres/:/docker-entrypoint-initdb.d/
      - ../postgres/data/:/var/lib/postgresql/data/
    command: postgres -c config_file=/usr/local/etc/postgres/postgres.conf
    ports:
      - ${POSTGRES_PORT_HOST}:${POSTGRES_PORT_CONTAINER}
    networks:
      - medplum_network
    hostname: ${POSTGRES_HOST}

  redis:
    container_name: medplum-redis
    image: redis:6
    command: redis-server --requirepass ${REDIS_PASSWORD}
    hostname: ${REDIS_HOST}
    ports:
      - ${REDIS_PORT_HOST}:${REDIS_PORT_CONTAINER}
    networks:
      - medplum_network

  proxy: 
    container_name: medplum-proxy
    image: nginx
    depends_on:
      - server
    volumes: 
      - ../nginx/templates/:/etc/nginx/templates/
      - ../nginx/conf.d/:/etc/nginx/conf.d/
    environment: 
      - MEDPLUM_BASE_URL=http://${MEDPLUM_HOST}:${MEDPLUM_PORT_CONTAINER}
      - KAILONA_SERVER_BASE_URL
      - KAILONA_SERVER_AUTH
    ports: 
      - ${NGINX_HTTP_PORT}:80
      - ${NGINX_HTTPS_PORT}:443
    networks: 
      - medplum_network
      - kailona_network

networks: 
  medplum_network: 
  kailona_network:
    driver: bridge 
